recovery_behaviors: false     # 是否允许恢复行为，恢复行为为原地旋转

shutdown_costmaps: false  # 当move_base进入inactive状态时候，决定是否停用节点的costmap (bool, default: false)

controller_frequency: 3.0  # 以Hz为单位的速率运行控制循环并向基座发送速度命令 (double, default: 20.0)

controller_patience: 3.0  # 在空间清理操作执行前，控制器会等待多长时间（秒）用来找出一个有效控制  (double, default: 15.0)

conservative_reset_dist: 5.0 # 当在地图中清理出空间时候，距离机器人几米远的障碍将会从costmap清除  (double, default: 3.0)

planner_frequency: 0.1  # 全局路径规划器loop速率 (double, default: 0.0)

planner_patience: 5.0  # 在空间清理操作执行前，路径规划器等待多长时间（秒）用来找出一个有效规划 (double, default: 5.0) 实验中发现局部地图经常会有移动障碍物遗留，并且不会去除，只有在移动后才能清除，部分只能在恢复行为后清除，所以有一个插件是专门用来做local障碍物清除的


oscillation_timeout: 10.0  # 执行修复操作之前，允许的震荡时间是几秒  (double, default: 0.0)

oscillation_distance: 0.3  # 机器人需要移动多少距离才算作没有震荡 (double, default: 0.5)


base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "global_planner/GlobalPlanner"