// Generated by gencpp from file ros_base_learning/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_BASE_LEARNING_MESSAGE_ADDTWOINTS_H
#define ROS_BASE_LEARNING_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_base_learning/AddTwoIntsRequest.h>
#include <ros_base_learning/AddTwoIntsResponse.h>


namespace ros_base_learning
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_base_learning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_base_learning::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_base_learning::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_base_learning::AddTwoInts > {
  static const char* value()
  {
    return "ros_base_learning/AddTwoInts";
  }

  static const char* value(const ::ros_base_learning::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_base_learning::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_base_learning::AddTwoInts >
template<>
struct MD5Sum< ::ros_base_learning::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_base_learning::AddTwoInts >::value();
  }
  static const char* value(const ::ros_base_learning::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_base_learning::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_base_learning::AddTwoInts >
template<>
struct DataType< ::ros_base_learning::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_base_learning::AddTwoInts >::value();
  }
  static const char* value(const ::ros_base_learning::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_base_learning::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_base_learning::AddTwoInts >
template<>
struct MD5Sum< ::ros_base_learning::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_base_learning::AddTwoInts >::value();
  }
  static const char* value(const ::ros_base_learning::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_base_learning::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_base_learning::AddTwoInts >
template<>
struct DataType< ::ros_base_learning::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_base_learning::AddTwoInts >::value();
  }
  static const char* value(const ::ros_base_learning::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASE_LEARNING_MESSAGE_ADDTWOINTS_H
