// Generated by gencpp from file ros_base_learning/robot_info.msg
// DO NOT EDIT!


#ifndef ROS_BASE_LEARNING_MESSAGE_ROBOT_INFO_H
#define ROS_BASE_LEARNING_MESSAGE_ROBOT_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_base_learning
{
template <class ContainerAllocator>
struct robot_info_
{
  typedef robot_info_<ContainerAllocator> Type;

  robot_info_()
    : header()
    , name()
    , age(0)
    , weight(0)
    , type(0)  {
    }
  robot_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , age(0)
    , weight(0)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef uint8_t _weight_type;
  _weight_type weight;

   typedef uint8_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOWN)
  #undef UNKNOWN
#endif
#if defined(_WIN32) && defined(TYPE_1)
  #undef TYPE_1
#endif
#if defined(_WIN32) && defined(TYPE_2)
  #undef TYPE_2
#endif

  enum {
    UNKNOWN = 0u,
    TYPE_1 = 1u,
    TYPE_2 = 2u,
  };


  typedef boost::shared_ptr< ::ros_base_learning::robot_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_base_learning::robot_info_<ContainerAllocator> const> ConstPtr;

}; // struct robot_info_

typedef ::ros_base_learning::robot_info_<std::allocator<void> > robot_info;

typedef boost::shared_ptr< ::ros_base_learning::robot_info > robot_infoPtr;
typedef boost::shared_ptr< ::ros_base_learning::robot_info const> robot_infoConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_base_learning::robot_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_base_learning::robot_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_base_learning::robot_info_<ContainerAllocator1> & lhs, const ::ros_base_learning::robot_info_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.weight == rhs.weight &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_base_learning::robot_info_<ContainerAllocator1> & lhs, const ::ros_base_learning::robot_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_base_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_base_learning::robot_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_base_learning::robot_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_base_learning::robot_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_base_learning::robot_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_base_learning::robot_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_base_learning::robot_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_base_learning::robot_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31d8314c5e0b46c76b66dca87e5e7ef9";
  }

  static const char* value(const ::ros_base_learning::robot_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31d8314c5e0b46c7ULL;
  static const uint64_t static_value2 = 0x6b66dca87e5e7ef9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_base_learning::robot_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_base_learning/robot_info";
  }

  static const char* value(const ::ros_base_learning::robot_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_base_learning::robot_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Robot info\n"
"uint8 UNKNOWN = 0\n"
"uint8 TYPE_1 = 1\n"
"uint8 TYPE_2 = 2\n"
"\n"
"Header header\n"
"string name\n"
"uint8 age\n"
"uint8 weight\n"
"uint8 type\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ros_base_learning::robot_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_base_learning::robot_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.weight);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_base_learning::robot_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_base_learning::robot_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "weight: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.weight);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASE_LEARNING_MESSAGE_ROBOT_INFO_H
